spring:
  sql:
    init:
      data-locations: classpath:initial_schema.sql
  datasource:
    url: jdbc:h2:mem:jdbc_template_example_db
    username: sa
    password: password
    driverClassName: org.h2.Driver
